version: "3.7"

services:
  cfhl:
    image: theonestack/cfhighlander:0.12.0
    volumes:
      - $HOME/.aws:/root/.aws
    env_file:
      - .env
  awscli:
    build:
      dockerfile: Dockerfile.awscli
      context: .